<a href="https://colab.research.google.com/github/bereznik/Anime-Recommendations/blob/master/Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Given that someone likes certain animes, which other animes this person might like?

Let's start by importing the needed datasets and modules



In [2]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.cluster import OPTICS

In [3]:
anime_original = pd.read_csv('/content/drive/My Drive/Anime analysis/anime.csv')
rating_original = pd.read_csv('/content/drive/My Drive/Anime analysis/rating.csv')

In [4]:
anime = anime_original.copy()
rating = rating_original.copy()

# Machine Learning recomendation system
### For this task we will use a colaborative system, in which we'll make recomendations based on the rating data of similar users.
Note that there are values of -1 in the rating column. This means that the user watched the film but didn't rate it. We'll choose to drop these values in this aproach. In another approach we may choose to input some values as the -1 rating is a significant proportion of the rating column, almost 15%

In [5]:
condition = rating.loc[rating.rating == -1,:].index
rating.drop(condition,inplace=True)
rating

user_id  anime_id  rating
47             1      8074      10
81             1     11617      10
83             1     11757      10
101            1     15451      10
153            2     11771      10
...          ...       ...     ...
7813732    73515     16512       7
7813733    73515     17187       9
7813734    73515     22145      10
7813735    73516       790       9
7813736    73516      8074       9

[6337241 rows x 3 columns]

In [6]:
# Creating an array with the Id's of the rated animes
anime_id_list = np.unique(rating.anime_id.values)
anime_id_list

array([    1,     5,     6, ..., 34349, 34367, 34475])

## Creation of the ratings matrix 

### We'll create a matrix such that the ij element of the matrix will be equal to the rating given by user "i" to the anime "j". Whenever the user didn't rate the anime the entry will be assigned to 0.

There is a simples way to accomplish this task. The .pivot( ) method does exactly that, but unfortunately our dataset is huge so we don't have enough memory to make the calculations.

To solve this problem, I came up with a function that leads to the same result but as a Sparse Matrix so we don't have to store all the values in memory!

In [7]:
from scipy.sparse import csr_matrix
from pandas.api.types import CategoricalDtype

user_c = CategoricalDtype(sorted(rating.user_id.unique()), ordered=True)
anime_c = CategoricalDtype(sorted(rating.anime_id.unique()), ordered=True)

row = rating.user_id.astype(user_c).cat.codes
col = rating.anime_id.astype(anime_c).cat.codes
sparse_matrix = csr_matrix((rating["rating"], (row, col)), \
                           shape=(user_c.categories.size, anime_c.categories.size))

In [8]:
### Importing the sparse matrix previously calculated
import scipy.sparse
X_sparse = scipy.sparse.load_npz("/content/drive/My Drive/Anime analysis/sparse_matrix.npz")




### The matrix is sparse because there are a ton of animes and obviously, most users didn't watch most of them

In [9]:
#Less than 1% of the entries belong to given ratings
sparcity = (X_sparse.nonzero()[0].shape[0])/(X_sparse.shape[0]*X_sparse.shape[1])
sparcity*100

0.9172178164972112

## In this approach, we'll use matrix factorization in order to predict all the entries which weren't assigned by the users, then we'll group similar users to finally give predictions about a new user
I've written a Gradient Descent algorithm to return two matrices P and Q such that their product approximates our original sparse matrix only at the entries that the users have given their ratings (non zero entries). This way the algorithm will learn the intrinsic taste of a user and will (hopefully!) generalize to the animes that weren't rated by the users. 

In [10]:
def Gradient_Descent(X):
    X_sparse = X/np.max(X)           # normalizing values
    print(X_sparse)
    n_factors = 100
    n_steps =  500                # optimized
    alpha = 0.01                   # optimized
    
    #initializing the vectors randomly:
    p = np.random.normal(0, .01, (X_sparse.shape[0], n_factors))
    q = np.random.normal(0, .01, (n_factors, X_sparse.shape[1]))      # changed so as to follow matrix multiplication rule
    
    for k in range(0,n_steps):
        for (i,j) in zip(X_sparse.nonzero()[0],X_sparse.nonzero()[1]):
            err = X_sparse[i,j] - np.dot(p[i, :],q[:, j])              # multiply whole row and column
            p[i, :] = p[i, :] + alpha*q[:, j]*err                      # update whole row and column
            q[:, j] = q[:, j] + alpha*p[i, :]*err                      # update whole row and column
    print(np.dot(p, q)) 
    p = p*np.sqrt(np.max(X))                         # matrix multiplication rule for normalized values
    q = q*np.sqrt(np.max(X))                         # matrix multiplication rule for normalized values
    return (p,q)   

In [11]:
p,q = Gradient_Descent(X_sparse)

In [12]:
#Loading both of the arrays
import numpy as np
p = np.load("/content/drive/My Drive/Anime analysis/P_100.npy")
q = np.load("/content/drive/My Drive/Anime analysis/Q_100.npy")
u = np.dot(p,q)
u

array([[ 8.05547392,  7.71305574,  9.6311547 , ...,  0.86857891,
         1.77497064,  2.97927456],
       [10.72737251, 10.4105446 ,  9.6147461 , ...,  3.85944463,
         2.26037376,  1.5800193 ],
       [ 7.3491924 ,  7.09325686,  5.82206622, ...,  4.01882358,
         2.49100806,  0.72991475],
       ...,
       [12.95052176, 12.08595885, 11.95415848, ...,  2.05773616,
         1.92105678,  3.47270485],
       [10.59713923,  9.64744348, 10.43794337, ...,  4.5994465 ,
         3.98210089,  2.89945446],
       [ 9.44646862,  9.12819814,  9.95487514, ...,  2.90826939,
         2.72424647,  1.34202599]])

### Great! Now we have a matrix with all the entries filled . We'll treat both the assigned values and the user-given values the same way without any distinction.

There is a problem, though... 

Let's see what the values of a well-known anime are. In this case let's take FullMetal Alchemist.

In [13]:
anime.loc[anime.name == 'Fullmetal Alchemist: Brotherhood']

anime_id                              name  ... rating members
1      5114  Fullmetal Alchemist: Brotherhood  ...   9.26  793665

[1 rows x 7 columns]

In [14]:
np.where(anime_id_list == 5114 )

(array([3936]),)

In [15]:
print('The mean is: ',u[:,3936].mean())
print('The standard deviation is: ',u[:,3936].std())

The mean is:  9.460341654958771
The standard deviation is:  1.1478887344063966


Some animes have means greater than 9 (with low standard deviation). That means that the algorithm will consistently choose these animes as top recomendations just because their overall scores are so high (as we will see when I show the full algorithm).

To solve this, I chose to reduce the values of the animes with mean greater than 9 and greater than 8 by using a weighted mean with those values and the mean of all the animes to give a chance for the lower rated ones to compete. Of course we need to reduce the ratings of the >9-mean animes more than the >8 animes.


In [16]:
#function to reduce the ratings of the best rated anime
def squeezing_top_values(u):
  p1 = 9        # paremeter to reduce the greater than 9-mean animes
  p2 = 200      # paremeter to reduce the greater than 8 and lower than 9 mean animes
  index1 = np.where(u.mean(axis=0)>9)
  index2 = np.where((u.mean(axis=0)>8) & (u.mean(axis=0)<9))
  k = u.mean()
  for i in index1:
    u[:,i] = (u[:,i]*p1 + k)/(p1+1)
  for i in index2:
    u[:,i] = (u[:,i]*p2 + k)/(p2+1)
  return u
u = squeezing_top_values(u)    
u

array([[ 8.0389772 ,  7.69826259,  9.60681878, ...,  0.86857891,
         1.77497064,  2.97927456],
       [10.69758276, 10.38233111,  9.59049181, ...,  3.85944463,
         2.26037376,  1.5800193 ],
       [ 7.33620953,  7.0815473 ,  5.81668099, ...,  4.01882358,
         2.49100806,  0.72991475],
       ...,
       [12.90967158, 12.04940998, 11.91826532, ...,  2.05773616,
         1.92105678,  3.47270485],
       [10.56799741,  9.62302652, 10.40959357, ...,  4.5994465 ,
         3.98210089,  2.89945446],
       [ 9.42305153,  9.10636449,  9.92892866, ...,  2.90826939,
         2.72424647,  1.34202599]])

In [17]:
# Now we have:
print('The mean now is: ',u[:,3936].mean())
print('The standard deviation now is: ',u[:,3936].std())

#That's better!

The mean now is:  8.988270899372202
The standard deviation now is:  1.033099860965757


### Let's assign the user input to a vector


In [18]:
''' This function takes the names and the ratings of the animes given 
by the new user and transforms them to the correct form such that the algorithm
will understand
'''

def user_input_scores(array):
    a = []
    scores = []
    for i in range(0,len(array)):
        a.append(anime.loc[anime.name == array[i][0]].anime_id.values[0]) 
    a = np.array(a)
    
    for i in range(0,len(anime_id_list) - len(array)):
        scores.append(0)
    
    for i in range(0,len(a)):
        index = np.where(anime_id_list == a[i])[0][0]
        scores.insert(index,array[i][1])
    scores = np.array(scores)
    return scores


### I've written a few customized lists of well known animes to test if the given recomendations make sense.

In [26]:
# shonen
y1 = [('Fullmetal Alchemist: Brotherhood',10),('Steins;Gate',10),('Gintama°',10),('Hunter x Hunter (2011)',10),
     ('Sen to Chihiro no Kamikakushi',10),('Shigatsu wa Kimi no Uso',7),('Cowboy Bebop',8),('Monster',5),
     ('Death Note',10),('Sword Art Online',10),('Tokyo Ghoul',10),
     ('Mirai Nikki',7)]
# sports
y2 = [('Haikyuu!!',10),('Kuroko no Basket',10),('Haikyuu!! Second Season',10),
      ('Free!',10),('Kuroko no Basket 2nd Season',10),('Hajime no Ippo',10),
      ('Slam Dunk',10),('Yowamushi Pedal',10),('Diamond no Ace',10),('Inazuma Eleven',10),
      ('Captain Tsubasa',10)]

y3 = [('Death Note',8),('Naruto',10)]

y4 = [('Haikyuu!!',10),('Diamond no Ace',10)]

y5 = [('Cowboy Bebop',10),('Monster',10)]


### Finally, below are all the functions needed to finish the recomendation process. The way that the recomendations will be given is as follows:

#### First, we'll use the KMeans algorithm to Cluster our users and see in which group our new user will be assigned to. To understand this in a high level you could think that the clustering will divide the users between the ones who like more shonen, the ones who like more sports animes and so on...

#### Then, we'll know the similar users with our new user.

#### Based on that we'll take the mean of all the animes ratings of those viewers and the recomended shows will be the ones with the highest means, simples isn't it?




In [20]:
#Function to determine the positions of the animes that the user has seen:

def position_seen_animes(y):
  scores = user_input_scores(y)
  position = np.where(scores!=0)[0]
  return position

# Function to create an array from the users matrix with only the animes the new user has seen

def user_scores_seen_animes(X,y):
  positions = position_seen_animes(y)
  return X[:,positions]

#Function to apply Kmeans algorithm to get similar viewers

def similar_users_position(X,y):
  
  n_clusters = 8 ### The best number after exhaustive tests

  X_transformed = user_scores_seen_animes(X,y)
  y_transformed = user_input_scores(y)[position_seen_animes(y)].reshape(1,-1)
  kmeans = KMeans(n_clusters = n_clusters).fit(X_transformed)
  group = kmeans.predict(y_transformed)
    
  (array_labels,n_labels) = np.unique(kmeans.labels_,return_counts = True) #test to see if the clustering was well done
  print(n_labels,group)
  similar_user_position = np.where(kmeans.labels_ == group)[0]
  return similar_user_position


#Function to take the mean scores of the similar users in order to rank the animes

def mean_scores(X,y):
  similar_users_scores = []
  
  index = similar_users_position(X,y) #similar users positions on the user matrix
  scores = np.zeros(len(anime_id_list)) #inicializing 

  for i in index:
    similar_users_scores.append(X[i])

  similar_users_scores = np.array(similar_users_scores)

  mean_scores = similar_users_scores.sum(axis = 0)/similar_users_scores.shape[0] # Getting the mean_scores

  return mean_scores

#Function to determine the positions of the best rated shows

def best_rated_shows(X,y):
  mean_marks = mean_scores(X,y)
  index = anime_id_list[np.argsort(mean_marks)[-35:]]
  return index

#Function to determine the names of the best rated shows

def names_best_rated_shows(X,y):
  index = best_rated_shows(X,y)
  for i in index:
        print(anime.loc[anime.anime_id == i,['name']])








In [27]:
a = names_best_rated_shows(u,y3)

[ 6812 14720  2847 11885 10363  8091  7526  7356] [3]
          name
3  Steins;Gate
                           name
72  Kuroko no Basket 2nd Season
             name
0  Kimi no Na wa.
           name
183  SKET Dance
                                        name
135  Rurouni Kenshin: Meiji Kenkaku Romantan
                           name
101  Magi: The Kingdom of Magic
                       name
14  Haikyuu!! Second Season
                              name
100  Diamond no Ace: Second Season
                                  name
13  Code Geass: Hangyaku no Lelouch R2
                                                 name
57  Ano Hi Mita Hana no Namae wo Bokutachi wa Mada...
                          name
29  Tengen Toppa Gurren Lagann
                   name
39  Bakuman. 3rd Season
                                                name
5  Haikyuu!!: Karasuno Koukou VS Shiratorizawa Ga...
       name
38  Monster
           name
304  D.Gray-man
                 name
66  Hellsing Ultimate
  